/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyAdminRouteImport } from './routes/verify-admin'
import { Route as ValidateAccessCodeRouteImport } from './routes/validate-access-code'
import { Route as SobreHalftoneRouteImport } from './routes/sobre-halftone'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AfiliadoRouteImport } from './routes/afiliado'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as ApiPublicInfinitepayWebhookRouteImport } from './routes/api/public/infinitepay-webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VerifyAdminRoute = VerifyAdminRouteImport.update({
  id: '/verify-admin',
  path: '/verify-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidateAccessCodeRoute = ValidateAccessCodeRouteImport.update({
  id: '/validate-access-code',
  path: '/validate-access-code',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreHalftoneRoute = SobreHalftoneRouteImport.update({
  id: '/sobre-halftone',
  path: '/sobre-halftone',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoRoute = AfiliadoRouteImport.update({
  id: '/afiliado',
  path: '/afiliado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInfinitepayWebhookRoute =
  ApiPublicInfinitepayWebhookRouteImport.update({
    id: '/api/public/infinitepay-webhook',
    path: '/api/public/infinitepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/afiliado': typeof AfiliadoRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/sobre-halftone': typeof SobreHalftoneRoute
  '/validate-access-code': typeof ValidateAccessCodeRoute
  '/verify-admin': typeof VerifyAdminRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/afiliado': typeof AfiliadoRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/sobre-halftone': typeof SobreHalftoneRoute
  '/validate-access-code': typeof ValidateAccessCodeRoute
  '/verify-admin': typeof VerifyAdminRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/afiliado': typeof AfiliadoRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/pedido': typeof PedidoRoute
  '/sobre-halftone': typeof SobreHalftoneRoute
  '/validate-access-code': typeof ValidateAccessCodeRoute
  '/verify-admin': typeof VerifyAdminRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/api/public/infinitepay-webhook': typeof ApiPublicInfinitepayWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/afiliado'
    | '/app'
    | '/login'
    | '/pedido'
    | '/sobre-halftone'
    | '/validate-access-code'
    | '/verify-admin'
    | '/api/stripe-webhook'
    | '/api/public/infinitepay-webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/afiliado'
    | '/app'
    | '/login'
    | '/pedido'
    | '/sobre-halftone'
    | '/validate-access-code'
    | '/verify-admin'
    | '/api/stripe-webhook'
    | '/api/public/infinitepay-webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/afiliado'
    | '/app'
    | '/login'
    | '/pedido'
    | '/sobre-halftone'
    | '/validate-access-code'
    | '/verify-admin'
    | '/api/stripe-webhook'
    | '/api/public/infinitepay-webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  AfiliadoRoute: typeof AfiliadoRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  PedidoRoute: typeof PedidoRoute
  SobreHalftoneRoute: typeof SobreHalftoneRoute
  ValidateAccessCodeRoute: typeof ValidateAccessCodeRoute
  VerifyAdminRoute: typeof VerifyAdminRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiPublicInfinitepayWebhookRoute: typeof ApiPublicInfinitepayWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-admin': {
      id: '/verify-admin'
      path: '/verify-admin'
      fullPath: '/verify-admin'
      preLoaderRoute: typeof VerifyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validate-access-code': {
      id: '/validate-access-code'
      path: '/validate-access-code'
      fullPath: '/validate-access-code'
      preLoaderRoute: typeof ValidateAccessCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-halftone': {
      id: '/sobre-halftone'
      path: '/sobre-halftone'
      fullPath: '/sobre-halftone'
      preLoaderRoute: typeof SobreHalftoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado': {
      id: '/afiliado'
      path: '/afiliado'
      fullPath: '/afiliado'
      preLoaderRoute: typeof AfiliadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/infinitepay-webhook': {
      id: '/api/public/infinitepay-webhook'
      path: '/api/public/infinitepay-webhook'
      fullPath: '/api/public/infinitepay-webhook'
      preLoaderRoute: typeof ApiPublicInfinitepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  AfiliadoRoute: AfiliadoRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  PedidoRoute: PedidoRoute,
  SobreHalftoneRoute: SobreHalftoneRoute,
  ValidateAccessCodeRoute: ValidateAccessCodeRoute,
  VerifyAdminRoute: VerifyAdminRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiPublicInfinitepayWebhookRoute: ApiPublicInfinitepayWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
